project:
  type: website
  output-dir: docs

website:
  title: "Leon Williams"
  favicon: favicon.ico
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/leonbaiyu/
      - icon: linkedin
        href: https://www.linkedin.com/in/leon-williams-313b071a6/
format:
  html:
    theme:
    - Simplex
    - custom.scss
    linestretch: 1.3

    css: styles.css



